name: yuyinting
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.5+6

environment:
  sdk: '>=2.19.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # 吐司插件
  fluttertoast: ^8.2.1
  # loading
  flutter_easyloading: ^3.0.5
  # 网络请求
  dio: ^4.0.6
  # 数据存贮
  shared_preferences: ^2.0.15
  # 屏幕适配
  flutter_screenutil: ^5.0.1
  # md5
  crypto: ^3.0.2
  # event_bus:
  event_bus: ^2.0.0
  # app升级
  package_info_plus: ^4.1.0
  ota_update: ^5.1.0
  # 打开外部浏览器
  url_launcher: ^6.1.5
  progress_dialog_null_safe: ^1.0.7
  open_file: ^3.3.2
  #  跳转路由
  auto_route: ^5.0.1
  # 日志打印
  logger: ^1.1.0
  # 选择器
  flutter_pickers: ^2.1.8
#  # 刷新控件
#  flutter_easyrefresh: ^2.2.2
  # 轮播图
  flutter_swiper: ^1.1.6
  # 图片选择器
  wechat_assets_picker: ^8.3.0
  # 相机
  wechat_camera_picker: ^3.0.0
  # 文件路径
  path_provider: ^2.0.5
  # 虚线边框
  dotted_border: ^2.0.0+3
  # 查看SVGA
  svgaplayer_flutter: ^2.2.0
  # 声网 Flutter SDK 依赖项，请使用最新版本的 agora_rtc_engine
  agora_rtc_engine: ^6.0.0
  # 环信
  im_flutter_sdk: ^4.1.3
  #  权限处理插件依赖项
  permission_handler: ^11.0.0
  # 验证码
  pin_code_fields: ^8.0.1
  # 刷新插件
  pull_to_refresh_flutter3: ^2.0.1
  # 动画库
  lottie: ^2.3.0
  # 选择相机
  image_picker: ^0.8.6
  # 录音
  flutter_sound: ^9.2.13
  audio_session: ^0.1.12
  # 图片压缩
  flutter_image_compress: ^1.1.3
  # 图片缓存
  cached_network_image: ^3.2.3
  # 播放视频
  video_player: ^2.7.0
  video_thumbnail: ^0.5.3
  flutter_cache_manager: ^3.1.2
  # 数据库
  sqflite: ^2.2.8
  # 表情库
  emoji_picker_flutter: ^1.5.2
  # 震动
  flutter_vibrate: ^1.3.0
  # 播放本地音频
  soundpool: ^2.3.0
  # 关于横竖屏转屏0
  auto_orientation: ^2.0.0
  # 保存网络图片
  image_gallery_saver: ^2.0.3
  # bugly
  flutter_bugly: ^0.4.4
  # 查看设备版本
  device_info_plus: ^8.0.0
  # 侧滑按钮
  flutter_slidable: ^0.6.0
  # 屏幕常亮
  screen: ^0.0.5
  # 加载h5页面
  webview_flutter: ^2.0.13
  # 跑马灯
  marquee: ^2.2.3
  # 权限
  path_provider_platform_interface: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/saiche/
    - assets/images/pt/
    - assets/images/cs/
    - assets/images/cy/
    - assets/images/car/
    - assets/images/dj/
    - assets/images/cj/
    - assets/images/hd/
    - assets/images/xz/
    - assets/svga/
    - assets/svga/gp/
    - assets/svga/shengbo/
    - assets/svga/touxiang/
    - assets/svga/zuoji/
    - assets/audio/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Impact
      fonts:
        - asset: assets/font/IMPACT.TTF
    - family: ARIAL
      fonts:
        - asset: assets/font/ARIAL.TTF
    - family: YOUSHEBIAOTIHEI
      fonts:
        - asset: assets/font/YOUSHEBIAOTIHEI-2.TTF
