import 'package:flutter/material.dart';
class MyColors{
  static const Color translucence = Color(0x80000000); //半透明
  static const Color b2 = Color(0x80B2B2B2); //半透明
  static const Color tBlack = Color(0xFF333333);
  static const Color themeRed = Color(0xFFE6464B);
  static const Color bgRed = Color(0xFFFAE1E1);
  static const Color bgGray = Color(0xFFF3F3F3);
  static const Color green = Color(0xFF00998A);
  static const Color e5 = Color(0xFFE5E5E5);
  static const Color g2 = Color(0xFF222222);
  static const Color g3 = Color(0xFF333333);
  static const Color g6 = Color(0xFF666666);
  static const Color g9 = Color(0xFF999999);
  static const Color d8 = Color(0xFFD8D8D8);
  static const Color f7 = Color(0xFFF7F6F9);
  static const Color blue = Color(0xFF3768F9);
  static const Color f4 = Color(0xFFF4F4F4);
  static const Color f5 = Color(0xFFF5F5F5);
  static const Color b8 = Color(0xFF9B9CCD);
  static const Color c2 = Color(0xFF2C2C2C);
  static const Color black_1 = Color(0xFF9B9CCD);
  static const Color black_3 = Color(0xFF333333);
  static const Color jianbian1 = Color(0xFF01A2ED);
  static const Color jianbian2 = Color(0xFF38E1FF);
  static const Color jianbian3 = Color(0xFF3197f2);
  static const Color jianbian4 = Color(0xFF4774F9);
  static const Color mine_exit = Color(0xFFFF4A23);
  static const Color home_hx = Color(0xFFE8EBF2);
  static const Color origin = Color(0xFFFF9601);
  static const Color btn_d = Color(0xFF8061FF);
  static const Color btn_a = Color(0xFF5b46b9);
  static const Color homeTopBG = Color(0xFF5b46b9);
  static const Color homeBG = Color(0xFFF6F7F8);
  static const Color homeSoucuoBG = Color(0xFF7D68C1);
  static const Color homeNoHave = Color(0xFFAFBACA);
  static const Color riBangBg = Color(0xFFA073F5);//日榜
  static const Color zhouBangBg = Color(0xFFBE99F7);//周榜
  static const Color pyWenZiBlue = Color(0xFF3E3155);//排行榜文字颜色
  static const Color pyWenZiPurple = Color(0xFF9171F6);//排行榜文字颜色
  static const Color pyWenZiGrey = Color(0xFF8E8997);//排行榜文字颜色
  static const Color dtPink = Color(0xFFFF6792);//动态 粉色
  static const Color dtBlue = Color(0xFF4BB6FF);//动态 蓝色
  static const Color f2 = Color(0xFFF2F2F2);
  static const Color f6 = Color(0xFFF6F6F6);
  static const Color careBlue = Color(0xFF7050F3);
  static const Color peopleBlue = Color(0xFF5C3097);
  static const Color peopleYellow = Color(0xFFF4E13F);
  static const Color peopleLiwu = Color(0xFFF4F2FF);
  static const Color peopleRed = Color(0xFFFF6161);
  static const Color peopleBlue2 = Color(0xFF8061FF);
  static const Color paiduiOrange = Color(0xFFEE7A4D);
  static const Color paiduiBlue = Color(0xFF4A9DF0);
  static const Color paiduiPurple = Color(0xFF8D74F5);
  static const Color mineGrey = Color(0xFF8D8FA2);
  static const Color mineOrange = Color(0xFFF3CF95);
  static const Color mineYellow = Color(0xFFFFF2D1);
  static const Color mineRed = Color(0xFFFA5353);
  static const Color minePink = Color(0xFFFFEBEF);
  static const Color walletPurple = Color(0xFFC12CFF);
  static const Color walletPink = Color(0xFFff4daf);
  static const Color walletBlue = Color(0xFF4d82ff);
  static const Color walletWZBlue = Color(0xFF974CF9);
  static const Color walletGrayBG = Color(0xFFFBFAFF);
  static const Color walletMingxi = Color(0xFF8061FF);
  static const Color dailiPurple = Color(0xFFEBD9EB);
  static const Color dailiPink = Color(0xFFEBD9D9);
  static const Color dailiBlue = Color(0xFFF2EFFF);
  static const Color dailiTime = Color(0xFFEEF4F4);
  static const Color dailiBaobiao = Color(0xFFF7F6F9);
  static const Color dailiShare= Color(0xFFDEDEE0);


}