import 'package:flutter/material.dart';
class MyColors{
  static const Color translucence = Color(0x80000000); //半透明
  static const Color b2 = Color(0x80B2B2B2); //半透明
  static const Color tBlack = Color(0xFF333333);
  static const Color themeRed = Color(0xFFE6464B);
  static const Color bgRed = Color(0xFFFAE1E1);
  static const Color bgGray = Color(0xFFF3F3F3);
  static const Color green = Color(0xFF00998A);
  static const Color e5 = Color(0xFFE5E5E5);
  static const Color g2 = Color(0xFF222222);
  static const Color g3 = Color(0xFF333333);
  static const Color g6 = Color(0xFF666666);
  static const Color g9 = Color(0xFF999999);
  static const Color d8 = Color(0xFFD8D8D8);
  static const Color f7 = Color(0xFFF7F6F9);
  static const Color blue = Color(0xFF3768F9);
  static const Color f4 = Color(0xFFF4F4F4);
  static const Color f5 = Color(0xFFF5F5F5);
  static const Color b8 = Color(0xFF9B9CCD);
  static const Color a5 = Color(0xFF5A5A5A);
  static const Color c2 = Color(0xFF2C2C2C);
  static const Color black_1 = Color(0xFF9B9CCD);
  static const Color black_3 = Color(0xFF333333);
  static const Color jianbian1 = Color(0xFF01A2ED);
  static const Color jianbian2 = Color(0xFF38E1FF);
  static const Color jianbian3 = Color(0xFF3197f2);
  static const Color jianbian4 = Color(0xFF4774F9);
  static const Color mine_exit = Color(0xFFFF4A23);
  static const Color home_hx = Color(0xFFE8EBF2);
  static const Color origin = Color(0xFFFF9601);
  static const Color btn_d = Color(0xFF8061FF);
  static const Color btn_a = Color(0xFF5b46b9);
  static const Color loginBtnP = Color(0xFF7F61FF);
  static const Color homeTopBG = Color(0xFF5b46b9);
  static const Color homeBG = Color(0xFFF6F7F8);
  static const Color homeSoucuoBG = Color(0xFF7D68C1);
  static const Color homeNoHave = Color(0xFFAFBACA);
  static const Color riBangBg = Color(0xFFA073F5);//日榜
  static const Color zhouBangBg = Color(0xFFBE99F7);//周榜
  static const Color pyWenZiBlue = Color(0xFF3E3155);//排行榜文字颜色
  static const Color pyWenZiPurple = Color(0xFF9171F6);//排行榜文字颜色
  static const Color pyWenZiGrey = Color(0xFF8E8997);//排行榜文字颜色
  static const Color dtPink = Color(0xFFFF6792);//动态 粉色
  static const Color dtBlue = Color(0xFF4BB6FF);//动态 蓝色
  static const Color f2 = Color(0xFFF2F2F2);
  static const Color f6 = Color(0xFFF6F6F6);
  static const Color careBlue = Color(0xFF7050F3);
  static const Color peopleBlue = Color(0xFF5C3097);
  static const Color peopleYellow = Color(0xFFF4E13F);
  static const Color peopleLiwu = Color(0xFFF4F2FF);
  static const Color peopleRed = Color(0xFFFF6161);
  static const Color peopleBlue2 = Color(0xFF8061FF);
  static const Color paiduiOrange = Color(0xFFEE7A4D);
  static const Color paiduiBlue = Color(0xFF4A9DF0);
  static const Color paiduiRed = Color(0xFFf04aa8);
  static const Color paiduiPurple = Color(0xFF8D74F5);
  static const Color paiduiDC = Color(0xFFf04a4a);
  static const Color paiduiXQ = Color(0xFF40dfc9);
  static const Color mineGrey = Color(0xFF8D8FA2);
  static const Color mineOrange = Color(0xFFF3CF95);
  static const Color mineYellow = Color(0xFFFFF2D1);
  static const Color mineRed = Color(0xFFFA5353);
  static const Color minePink = Color(0xFFFFEBEF);
  static const Color walletPurple = Color(0xFFC12CFF);
  static const Color walletPink = Color(0xFFff4daf);
  static const Color walletBlue = Color(0xFF4d82ff);
  static const Color walletWZBlue = Color(0xFF974CF9);
  static const Color walletGrayBG = Color(0xFFFBFAFF);
  static const Color walletMingxi = Color(0xFF8061FF);
  static const Color dailiPurple = Color(0xFFEBD9EB);
  static const Color dailiPink = Color(0xFFEBD9D9);
  static const Color dailiBlue = Color(0xFFF2EFFF);
  static const Color dailiTime = Color(0xFFEEF4F4);
  static const Color dailiBaobiao = Color(0xFFF7F6F9);
  static const Color dailiShare= Color(0xFFDEDEE0);
  static const Color loginBlue= Color(0xFF6ABCF4);
  static const Color loginBlue2= Color(0xFFDDF0FD);
  static const Color loginPink= Color(0xFFFAACCE);
  static const Color loginPink2= Color(0xFFF9D7E6);
  static const Color loginPurple = Color(0xFFD7D0FB);
  static const Color messagePurple = Color(0xFFEAE7F7);
  static const Color zhuangbanBg = Color(0xFF1F1531);
  static const Color zhuangbanWZBg = Color(0xFF352C45);
  static const Color zhuangbanWZ = Color(0xFFABA7B2);
  static const Color zhuangbanBottomBG = Color(0xFF292940);
  static const Color guizuYellow = Color(0xFFFFCB88);
  static const Color guizuYellow2 = Color(0xFF492F09);
  static const Color guizuGrey = Color(0xFF9386AA);
  static const Color guizuBlack = Color(0xFF3C2A5C);
  static const Color roomID = Color(0xFFBFCCE9);
  static const Color roomHot = Color(0xFF18293E);
  static const Color roomMaiWZ = Color(0xFF97A2AE);
  static const Color roomMaiLiao = Color(0xFF5590B1);
  static const Color roomMaiLiao2 = Color(0xFF253F55);
  static const Color roomMaiLiao3 = Color(0xFF69809F);
  static const Color roomShangMaiWZ = Color(0xFFCCD9F7);
  static const Color roomTCBlack = Color(0xFF07061E);
  static const Color roomTCWZ1 = Color(0xFF858CA9);
  static const Color roomTCWZ2 = Color(0xFFD5E0FF);
  static const Color roomTCWZ3 = Color(0xFF8C94B3);
  static const Color roomTCYellow = Color(0xFFF7D465);
  static const Color roomTCWhitw = Color(0xFFD2DDFC);
  static const Color roomPHWZBlack = Color(0xFF14222E);
  static const Color roomBlue = Color(0xFF3982F7);
  static const Color roomMessageYellow = Color(0xFFCEB258);
  static const Color roomMessageYellow2 = Color(0xFFFFDC6D);
  static const Color roomMessageBlackBG = Color(0xFF201F3B);
  static const Color roomMessageLiaotian = Color(0xFF43456E);
  static const Color roomPassXian = Color(0xFF363657);
  static const Color roomCirle = Color(0xFF2F2876);
  /// 等级描边字体
  static const Color djOne = Color(0xFFFAFAFD);
  static const Color djOneM = Color(0xFF3D4C57);
  static const Color djTwoM = Color(0xFF1A0096);
  static const Color djThreeM = Color(0xFF025393);
  static const Color djFourM = Color(0xFF025C69);
  static const Color djFiveM = Color(0xFF096F35);
  static const Color djSixM = Color(0xFFCC610A);
  static const Color djSevenM = Color(0xFFFF7262);
  static const Color djEightM = Color(0xFFFF67F8);
  static const Color djNineM = Color(0xFFE7900A);
  /// 老板位渐变色
  static const Color lbL = Color(0xFF6ffffd);
  static const Color lbR = Color(0xFFf8fec4);
  /// 转盘颜色
  static const Color zpBG = Color(0xFF100B43);
  static const Color zpBGJ1 = Color(0xFFF9F0BF);
  static const Color zpBGJ2 = Color(0xFFFFB48C);
  static const Color zpWZ1 = Color(0xFFDF4424);
  static const Color zpJD = Color(0xFF1644ce);
  static const Color chatBlue = Color(0xFFE4DFF7);
  static const Color zpJLYellow = Color(0xFFD9C4AB);
  static const Color zpJLHX = Color(0xFF76819F);
  static const Color zpGZYellow = Color(0xFFFEC25E);
  static const Color mfZGBlue = Color(0xFF7EEEFF);
  static const Color zpJCWhite = Color(0xFFACA3C5);
  static const Color zpJCWhite2 = Color(0xFF9195C5);
  static const Color loginBG = Color(0xFFFBDFFD);
  static const Color CarBG = Color(0xFF051339);
  static const Color CarXian = Color(0xFF625F8F);
  static const Color CarZJ = Color(0xFF4D1DAD);
  static const Color roomXZ1 = Color(0xFF2D2F4E);
  static const Color roomXZ2 = Color(0xFF201E3B);
  static const Color zp1 = Color(0xFF8F4E58);
  static const Color yzZi1 = Color(0xFF05184F);
  static const Color yzZi2 = Color(0xFF3794B0);
  /// 中奖公屏礼物颜色
  static const Color zjZ1 = Color(0xFFE295FF);
  static const Color zjZ2 = Color(0xFF9DFFBF);
  static const Color zjZ3 = Color(0xFF96FBFF);
  static const Color zjZ4 = Color(0xFFFFFB98);

}