/// 符号转图标使用
import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';
const List<CategoryEmoji> defaultEmojiSets = [

  CategoryEmoji(Category.SMILEYS, [
  Emoji('😀', 'Grinning Face'),
  Emoji('😃', 'Grinning Face With Big Eyes'),
  Emoji('😄', 'Grinning Face With Smiling Eyes'),
  Emoji('😁', 'Beaming Face With Smiling Eyes'),
  Emoji('😆', 'Grinning Squinting Face'),
  Emoji('😅', 'Grinning Face With Sweat'),
  Emoji('🤣', 'Rolling on the Floor Laughing'),
  Emoji('😂', 'Face With Tears of Joy'),
  Emoji('🙂', 'Slightly Smiling Face'),
  Emoji('🙃', 'Upside-Down Face'),
  Emoji('😉', 'Winking Face'),
  Emoji('😊', 'Smiling Face With Smiling Eyes'),
  Emoji('😇', 'Smiling Face With Halo'),
  Emoji('🥰', 'Smiling Face With Hearts'),
  Emoji('😍', 'Smiling Face With Heart-Eyes'),
  Emoji('🤩', 'Star-Struck'),
  Emoji('😘', 'Face Blowing a Kiss'),
  Emoji('😗', 'Kissing Face'),
  Emoji('☺', 'Smiling Face'),
  Emoji('😚', 'Kissing Face With Closed Eyes'),
  Emoji('😙', 'Kissing Face With Smiling Eyes'),
  Emoji('😋', 'Face Savoring Food'),
  Emoji('😛', 'Face With Tongue'),
  Emoji('😜', 'Winking Face With Tongue'),
  Emoji('🤪', 'Zany Face'),
  Emoji('😝', 'Squinting Face With Tongue'),
  Emoji('🤑', 'Money-Mouth Face'),
  Emoji('🤗', 'Hugging Face'),
  Emoji('🫣', 'Face with Peeking Eye'),
  Emoji('🤭', 'Face With Hand Over Mouth'),
  Emoji('🫢', 'Face with Open Eyes and Hand Over Mouth'),
  Emoji('🫡', 'Saluting Face'),
  Emoji('🤫', 'Shushing Face'),
  Emoji('🫠', 'Melting Face'),
  Emoji('🤔', 'Thinking Face'),
  Emoji('🤐', 'Zipper-Mouth Face'),
  Emoji('🤨', 'Face With Raised Eyebrow'),
  Emoji('😐', 'Neutral Face'),
  Emoji('🫤', 'Face with Diagonal Mouth'),
  Emoji('😑', 'Expressionless Face'),
  Emoji('😶', 'Face Without Mouth'),
  Emoji('🫥', 'Dotted Line Face'),
  Emoji('😏', 'Smirking Face'),
  Emoji('😒', 'Unamused Face'),
  Emoji('🙄', 'Face With Rolling Eyes'),
  Emoji('😬', 'Grimacing Face'),
  Emoji('🤥', 'Lying Face'),
  Emoji('😌', 'Relieved Face'),
  Emoji('😔', 'Pensive Face'),
  Emoji('🥹', 'Face Holding Back Tears'),
  Emoji('😪', 'Sleepy Face'),
  Emoji('🤤', 'Drooling Face'),
  Emoji('😴', 'Sleeping Face'),
  Emoji('😷', 'Face With Medical Mask'),
  Emoji('🤒', 'Face With Thermometer'),
  Emoji('🤕', 'Face With Head-Bandage'),
  Emoji('🤢', 'Nauseated Face'),
  Emoji('🤮', 'Face Vomiting'),
  Emoji('🤧', 'Sneezing Face'),
  Emoji('🥵', 'Hot Face'),
  Emoji('🥶', 'Cold Face'),
  Emoji('🥴', 'Woozy Face'),
  Emoji('😵', 'Dizzy Face'),
  Emoji('🤯', 'Exploding Head'),
  Emoji('🤠', 'Cowboy Hat Face'),
  Emoji('🥳', 'Partying Face'),
  Emoji('😎', 'Smiling Face With Sunglasses'),
  Emoji('🤓', 'Nerd Face'),
  Emoji('🧐', 'Face With Monocle'),
  Emoji('😕', 'Confused Face'),
  Emoji('😟', 'Worried Face'),
  Emoji('🙁', 'Slightly Frowning Face'),
  Emoji('☹', 'Frowning Face'),
  Emoji('😮', 'Face With Open Mouth'),
  Emoji('😯', 'Hushed Face'),
  Emoji('😲', 'Astonished Face'),
  Emoji('😳', 'Flushed Face'),
  Emoji('🥺', 'Pleading Face'),
  Emoji('😦', 'Frowning Face With Open Mouth'),
  Emoji('😧', 'Anguished Face'),
  Emoji('😨', 'Fearful Face'),
  Emoji('😰', 'Anxious Face With Sweat'),
  Emoji('😥', 'Sad but Relieved Face'),
  Emoji('😢', 'Crying Face'),
  Emoji('😭', 'Loudly Crying Face'),
  Emoji('😱', 'Face Screaming in Fear'),
  Emoji('😖', 'Confounded Face'),
  Emoji('😣', 'Persevering Face'),
  Emoji('😞', 'Disappointed Face'),
  Emoji('😓', 'Downcast Face With Sweat'),
  Emoji('😩', 'Weary Face'),
  Emoji('😫', 'Tired Face'),
  Emoji('😤', 'Face With Steam From Nose'),
  Emoji('😡', 'Pouting Face'),
  Emoji('😠', 'Angry Face'),
  Emoji('🤬', 'Face With Symbols on Mouth'),
  Emoji('😈', 'Smiling Face With Horns'),
  Emoji('👿', 'Angry Face With Horns'),
  Emoji('💀', 'Skull'),
  Emoji('☠', 'Skull and Crossbones'),
  Emoji('💩', 'Pile of Poo'),
  Emoji('🤡', 'Clown Face'),
  Emoji('👹', 'Ogre'),
  Emoji('👺', 'Goblin'),
  Emoji('👻', 'Ghost'),
  Emoji('👽', 'Alien'),
  Emoji('👾', 'Alien Monster'),
  Emoji('🤖', 'Robot Face'),
  Emoji('😺', 'Grinning Cat Face'),
  Emoji('😸', 'Grinning Cat Face With Smiling Eyes'),
  Emoji('😹', 'Cat Face With Tears of Joy'),
  Emoji('😻', 'Smiling Cat Face With Heart-Eyes'),
  Emoji('😼', 'Cat Face With Wry Smile'),
  Emoji('😽', 'Kissing Cat Face'),
  Emoji('🙀', 'Weary Cat Face'),
  Emoji('😿', 'Crying Cat Face'),
  Emoji('😾', 'Pouting Cat Face'),
  Emoji('🫶', 'Heart Hands', hasSkinTone: true),
  Emoji('👋', 'Waving Hand', hasSkinTone: true),
  Emoji('🤚', 'Raised Back of Hand', hasSkinTone: true),
  Emoji('🖐', 'Hand With Fingers Splayed', hasSkinTone: true),
  Emoji('✋', 'Raised Hand', hasSkinTone: true),
  Emoji('🖖', 'Vulcan Salute', hasSkinTone: true),
  Emoji('👌', 'OK Hand', hasSkinTone: true),
  Emoji('🤌', 'Pinched Fingers', hasSkinTone: true),
  Emoji('🤏', 'Pinching Hand', hasSkinTone: true),
  Emoji('🫳', 'Palm Down Hand', hasSkinTone: true),
  Emoji('🫴', 'Palm Up Hand', hasSkinTone: true),
  Emoji('✌️', 'Victory Hand', hasSkinTone: true),
  Emoji('🫰', 'Hand with Index Finger and Thumb Crossed', hasSkinTone: true),
  Emoji('🤞', 'Crossed Fingers', hasSkinTone: true),
  Emoji('🤟', 'Love-You Gesture', hasSkinTone: true),
  Emoji('🤘', 'Sign of the Horns', hasSkinTone: true),
  Emoji('🤙', 'Call Me Hand', hasSkinTone: true),
  Emoji('👈', 'Backhand Index Pointing Left', hasSkinTone: true),
  Emoji('👉', 'Backhand Index Pointing Right', hasSkinTone: true),
  Emoji('👆', 'Backhand Index Pointing Up', hasSkinTone: true),
  Emoji('🖕', 'Middle Finger', hasSkinTone: true),
  Emoji('👇', 'Backhand Index Pointing Down', hasSkinTone: true),
  Emoji('☝', 'Index Pointing Up', hasSkinTone: true),
  Emoji('👍', 'Thumbs Up', hasSkinTone: true),
  Emoji('👎', 'Thumbs Down', hasSkinTone: true),
  Emoji('✊', 'Raised Fist', hasSkinTone: true),
  Emoji('👊', 'Oncoming Fist', hasSkinTone: true),
  Emoji('🤛', 'Left-Facing Fist', hasSkinTone: true),
  Emoji('🤜', 'Right-Facing Fist', hasSkinTone: true),
  Emoji('🫲', 'Leftwards Hand', hasSkinTone: true),
  Emoji('🫱', 'Rightwards Hand', hasSkinTone: true),
  Emoji('👏', 'Clapping Hands', hasSkinTone: true),
  Emoji('🙌', 'Raising Hands', hasSkinTone: true),
  Emoji('👐', 'Open Hands', hasSkinTone: true),
  Emoji('🤲', 'Palms Up Together', hasSkinTone: true),
  Emoji('🤝', 'Handshake', hasSkinTone: true),
  Emoji('🙏', 'Folded Hands', hasSkinTone: true),
  Emoji('🫵', 'Index Pointing at the Viewer', hasSkinTone: true),
  Emoji('✍', 'Writing Hand', hasSkinTone: true),
  Emoji('💅', 'Nail Polish', hasSkinTone: true),
  Emoji('🤳', 'Selfie', hasSkinTone: true),
  Emoji('💪', 'Flexed Biceps', hasSkinTone: true),
  Emoji('🦵', 'Leg', hasSkinTone: true),
  Emoji('🦶', 'Foot', hasSkinTone: true),
  Emoji('👂', 'Ear', hasSkinTone: true),
  Emoji('👃', 'Nose', hasSkinTone: true),
  Emoji('🧠', 'Brain'),
  Emoji('🦴', 'Bone'),
  Emoji('👀', 'Eyes'),
  Emoji('👁', 'Eye'),
  Emoji('💋', 'Kiss Mark'),
  Emoji('👄', 'Mouth'),
  Emoji('🫦', 'Biting Lip'),
  Emoji('🦷', 'Tooth'),
  Emoji('👅', 'Tongue'),
  Emoji('👶', 'Baby', hasSkinTone: true),
  Emoji('🧒', 'Child', hasSkinTone: true),
  Emoji('👦', 'Boy', hasSkinTone: true),
  Emoji('👧', 'Girl', hasSkinTone: true),
  Emoji('🧑', 'Person', hasSkinTone: true),
  Emoji('👨', 'Man', hasSkinTone: true),
  Emoji('🧔', 'Man: Beard', hasSkinTone: true),
  Emoji('👱', 'Man: Blond Hair', hasSkinTone: true),
  Emoji('👨‍🦰', 'Man: Red Hair', hasSkinTone: true),
  Emoji('👨‍🦱', 'Man: Curly Hair', hasSkinTone: true),
  Emoji('👨‍🦳', 'Man: White Hair', hasSkinTone: true),
  Emoji('👨‍🦲', 'Man: Bald', hasSkinTone: true),
  Emoji('👩', 'Woman', hasSkinTone: true),
  Emoji('👱‍♀️', 'Woman: Blond Hair', hasSkinTone: true),
  Emoji('👩‍🦰', 'Woman: Red Hair', hasSkinTone: true),
  Emoji('👩‍🦱', 'Woman: Curly Hair', hasSkinTone: true),
  Emoji('👩‍🦳', 'Woman: White Hair', hasSkinTone: true),
  Emoji('👩‍🦲', 'Woman: Bald', hasSkinTone: true),
  Emoji('🧓', 'Older Person', hasSkinTone: true),
  Emoji('👴', 'Old Man', hasSkinTone: true),
  Emoji('👵', 'Old Woman', hasSkinTone: true),
  Emoji('🙍‍♂️', 'Man Frowning', hasSkinTone: true),
  Emoji('🙍‍♀️', 'Woman Frowning', hasSkinTone: true),
  Emoji('🙎‍♂️', 'Man Pouting', hasSkinTone: true),
  Emoji('🙎‍♀️', 'Woman Pouting', hasSkinTone: true),
  Emoji('🙅‍♂️', 'Man Gesturing No', hasSkinTone: true),
  Emoji('🙅‍♀️', 'Woman Gesturing No', hasSkinTone: true),
  Emoji('🙆‍♂️', 'Man Gesturing OK', hasSkinTone: true),
  Emoji('🙆‍♀️', 'Woman Gesturing OK', hasSkinTone: true),
  Emoji('💁‍♂️', 'Man Tipping Hand', hasSkinTone: true),
  Emoji('💁‍♀️', 'Woman Tipping Hand', hasSkinTone: true),
  Emoji('🙋‍♂️', 'Man Raising Hand', hasSkinTone: true),
  Emoji('🙋‍♀️', 'Woman Raising Hand', hasSkinTone: true),
  Emoji('🙇‍♂️', 'Man Bowing', hasSkinTone: true),
  Emoji('🙇‍♀️', 'Woman Bowing', hasSkinTone: true),
  Emoji('🤦‍♂️', 'Man Facepalming', hasSkinTone: true),
  Emoji('🤦‍♀️', 'Woman Facepalming', hasSkinTone: true),
  Emoji('🤷‍♂️', 'Man Shrugging', hasSkinTone: true),
  Emoji('🤷‍♀️', 'Woman Shrugging', hasSkinTone: true),
  Emoji('👨‍⚕️', 'Man Health Worker', hasSkinTone: true),
  Emoji('👩‍⚕️', 'Woman Health Worker', hasSkinTone: true),
  Emoji('👨‍🎓', 'Man Student', hasSkinTone: true),
  Emoji('👩‍🎓', 'Woman Student', hasSkinTone: true),
  Emoji('👨‍🏫', 'Man Teacher', hasSkinTone: true),
  Emoji('👩‍🏫', 'Woman Teacher', hasSkinTone: true),
  Emoji('👨‍⚖️', 'Man Judge', hasSkinTone: true),
  Emoji('👩‍⚖️', 'Woman Judge', hasSkinTone: true),
  Emoji('👨‍🌾', 'Man Farmer', hasSkinTone: true),
  Emoji('👩‍🌾', 'Woman Farmer', hasSkinTone: true),
  Emoji('👨‍🍳', 'Man Cook', hasSkinTone: true),
  Emoji('👩‍🍳', 'Woman Cook', hasSkinTone: true),
  Emoji('👨‍🔧', 'Man Mechanic', hasSkinTone: true),
  Emoji('👩‍🔧', 'Woman Mechanic', hasSkinTone: true),
  Emoji('👨‍🏭', 'Man Factory Worker', hasSkinTone: true),
  Emoji('👩‍🏭', 'Woman Factory Worker', hasSkinTone: true),
  Emoji('👨‍💼', 'Man Office Worker', hasSkinTone: true),
  Emoji('👩‍💼', 'Woman Office Worker', hasSkinTone: true),
  Emoji('👨‍🔬', 'Man Scientist', hasSkinTone: true),
  Emoji('👩‍🔬', 'Woman Scientist', hasSkinTone: true),
  Emoji('👨‍💻', 'Man Technologist', hasSkinTone: true),
  Emoji('👩‍💻', 'Woman Technologist', hasSkinTone: true),
  Emoji('👨‍🎤', 'Man Singer', hasSkinTone: true),
  Emoji('👩‍🎤', 'Woman Singer', hasSkinTone: true),
  Emoji('👨‍🎨', 'Man Artist', hasSkinTone: true),
  Emoji('👩‍🎨', 'Woman Artist', hasSkinTone: true),
  Emoji('👨‍✈️', 'Man Pilot', hasSkinTone: true),
  Emoji('👩‍✈️', 'Woman Pilot', hasSkinTone: true),
  Emoji('👨‍🚀', 'Man Astronaut', hasSkinTone: true),
  Emoji('👩‍🚀', 'Woman Astronaut', hasSkinTone: true),
  Emoji('👨‍🚒', 'Man Firefighter', hasSkinTone: true),
  Emoji('👩‍🚒', 'Woman Firefighter', hasSkinTone: true),
  Emoji('👮‍♂️', 'Man Police Officer', hasSkinTone: true),
  Emoji('👮‍♀️', 'Woman Police Officer', hasSkinTone: true),
  Emoji('🕵️‍♂️', 'Man Detective', hasSkinTone: true),
  Emoji('🕵️‍♀️', 'Woman Detective', hasSkinTone: true),
  Emoji('💂‍♂️', 'Man Guard', hasSkinTone: true),
  Emoji('💂‍♀️', 'Woman Guard', hasSkinTone: true),
  Emoji('👷‍♂️', 'Man Construction Worker', hasSkinTone: true),
  Emoji('👷‍♀️', 'Woman Construction Worker', hasSkinTone: true),
  Emoji('🤴', 'Prince', hasSkinTone: true),
  Emoji('👸', 'Princess', hasSkinTone: true),
  Emoji('👳‍♂️', 'Man Wearing Turban', hasSkinTone: true),
  Emoji('👳‍♀️', 'Woman Wearing Turban', hasSkinTone: true),
  Emoji('👲', 'Man With Chinese Cap', hasSkinTone: true),
  Emoji('🧕', 'Woman With Headscarf', hasSkinTone: true),
  Emoji('🤵', 'Man in Tuxedo', hasSkinTone: true),
  Emoji('👰', 'Bride With Veil', hasSkinTone: true),
  Emoji('🤰', 'Pregnant Woman', hasSkinTone: true),
  Emoji('🤱', 'Breast-Feeding', hasSkinTone: true),
  Emoji('👼', 'Baby Angel', hasSkinTone: true),
  Emoji('🎅', 'Santa Claus', hasSkinTone: true),
  Emoji('🤶', 'Mrs. Claus', hasSkinTone: true),
  Emoji('🦸‍♂️', 'Man Superhero', hasSkinTone: true),
  Emoji('🦸‍♀️', 'Woman Superhero', hasSkinTone: true),
  Emoji('🦹‍♂️', 'Man Supervillain', hasSkinTone: true),
  Emoji('🦹‍♀️', 'Woman Supervillain', hasSkinTone: true),
  Emoji('🧙‍♂️', 'Man Mage', hasSkinTone: true),
  Emoji('🧙‍♀️', 'Woman Mage', hasSkinTone: true),
  Emoji('🧚‍♂️', 'Man Fairy', hasSkinTone: true),
  Emoji('🧚‍♀️', 'Woman Fairy', hasSkinTone: true),
  Emoji('🧛‍♂️', 'Man Vampire', hasSkinTone: true),
  Emoji('🧛‍♀️', 'Woman Vampire', hasSkinTone: true),
  Emoji('🧜‍♂️', 'Merman', hasSkinTone: true),
  Emoji('🧜‍♀️', 'Mermaid', hasSkinTone: true),
  Emoji('🧝‍♂️', 'Man Elf', hasSkinTone: true),
  Emoji('🧝‍♀️', 'Woman Elf', hasSkinTone: true),
  Emoji('🧞‍♂️', 'Man Genie'),
  Emoji('🧞‍♀️', 'Woman Genie'),
  Emoji('🧟‍♂️', 'Man Zombie'),
  Emoji('🧟‍♀️', 'Woman Zombie'),
  Emoji('💆‍♂️', 'Man Getting Massage', hasSkinTone: true),
  Emoji('💆‍♀️', 'Woman Getting Massage', hasSkinTone: true),
  Emoji('💇‍♂️', 'Man Getting Haircut', hasSkinTone: true),
  Emoji('💇‍♀️', 'Woman Getting Haircut', hasSkinTone: true),
  Emoji('🚶‍♂️', 'Man Walking', hasSkinTone: true),
  Emoji('🚶‍♀️', 'Woman Walking', hasSkinTone: true),
  Emoji('🏃‍♂️', 'Man Running', hasSkinTone: true),
  Emoji('🏃‍♀️', 'Woman Running', hasSkinTone: true),
  Emoji('🕺', 'Man Dancing', hasSkinTone: true),
  Emoji('💃', 'Woman Dancing', hasSkinTone: true),
  Emoji('🕴', 'Man in Suit Levitating', hasSkinTone: true),
  Emoji('👯‍♂️', 'Men With Bunny Ears'),
  Emoji('👯‍♀️', 'Women With Bunny Ears'),
  Emoji('🧖‍♂️', 'Man in Steamy Room', hasSkinTone: true),
  Emoji('🧖‍♀️', 'Woman in Steamy Room', hasSkinTone: true),
  Emoji('🧘', 'Person in Lotus Position', hasSkinTone: true),
  Emoji('👭', 'Women Holding Hands', hasSkinTone: true),
  Emoji('👫', 'Woman and Man Holding Hands', hasSkinTone: true),
  Emoji('👬', 'Men Holding Hands', hasSkinTone: true),
  Emoji('💏', 'Kiss'),
  Emoji('👨‍❤️‍💋‍👨', 'Kiss: Man, Man'),
  Emoji('👩‍❤️‍💋‍👩', 'Kiss: Woman, Woman'),
  Emoji('💑', 'Couple With Heart'),
  Emoji('👨‍❤️‍👨', 'Couple With Heart: Man, Man'),
  Emoji('👩‍❤️‍👩', 'Couple With Heart: Woman, Woman'),
  Emoji('👪', 'Family'),
  Emoji('👨‍👩‍👦', 'Family: Man, Woman, Boy'),
  Emoji('👨‍👩‍👧', 'Family: Man, Woman, Girl'),
  Emoji('👨‍👩‍👧‍👦', 'Family: Man, Woman, Girl, Boy'),
  Emoji('👨‍👩‍👦‍👦', 'Family: Man, Woman, Boy, Boy'),
  Emoji('👨‍👩‍👧‍👧', 'Family: Man, Woman, Girl, Girl'),
  Emoji('👨‍👨‍👦', 'Family: Man, Man, Boy'),
  Emoji('👨‍👨‍👧', 'Family: Man, Man, Girl'),
  Emoji('👨‍👨‍👧‍👦', 'Family: Man, Man, Girl, Boy'),
  Emoji('👨‍👨‍👦‍👦', 'Family: Man, Man, Boy, Boy'),
  Emoji('👨‍👨‍👧‍👧', 'Family: Man, Man, Girl, Girl'),
  Emoji('👩‍👩‍👦', 'Family: Woman, Woman, Boy'),
  Emoji('👩‍👩‍👧', 'Family: Woman, Woman, Girl'),
  Emoji('👩‍👩‍👧‍👦', 'Family: Woman, Woman, Girl, Boy'),
  Emoji('👩‍👩‍👦‍👦', 'Family: Woman, Woman, Boy, Boy'),
  Emoji('👩‍👩‍👧‍👧', 'Family: Woman, Woman, Girl, Girl'),
  Emoji('👨‍👦', 'Family: Man, Boy'),
  Emoji('👨‍👦‍👦', 'Family: Man, Boy, Boy'),
  Emoji('👨‍👧', 'Family: Man, Girl'),
  Emoji('👨‍👧‍👦', 'Family: Man, Girl, Boy'),
  Emoji('👨‍👧‍👧', 'Family: Man, Girl, Girl'),
  Emoji('👩‍👦', 'Family: Woman, Boy'),
  Emoji('👩‍👦‍👦', 'Family: Woman, Boy, Boy'),
  Emoji('👩‍👧', 'Family: Woman, Girl'),
  Emoji('👩‍👧‍👦', 'Family: Woman, Girl, Boy'),
  Emoji('👩‍👧‍👧', 'Family: Woman, Girl, Girl'),
  Emoji('🗣', 'Speaking Head'),
  Emoji('👤', 'Bust in Silhouette'),
  Emoji('👥', 'Busts in Silhouette'),
  Emoji('👣', 'Footprints'),
  Emoji('🧳', 'Luggage'),
  Emoji('🌂', 'Closed Umbrella'),
  Emoji('☂', 'Umbrella'),
  Emoji('🧵', 'Thread'),
  Emoji('🧶', 'Yarn'),
  Emoji('👓', 'Glasses'),
  Emoji('🕶', 'Sunglasses'),
  Emoji('🥽', 'Goggles'),
  Emoji('🥼', 'Lab Coat'),
  Emoji('👔', 'Necktie'),
  Emoji('👕', 'T-Shirt'),
  Emoji('👖', 'Jeans'),
  Emoji('🧣', 'Scarf'),
  Emoji('🧤', 'Gloves'),
  Emoji('🧥', 'Coat'),
  Emoji('🧦', 'Socks'),
  Emoji('👗', 'Dress'),
  Emoji('👘', 'Kimono'),
  Emoji('👙', 'Bikini'),
  Emoji('👚', 'Woman’s Clothes'),
  Emoji('👛', 'Purse'),
  Emoji('👜', 'Handbag'),
  Emoji('👝', 'Clutch Bag'),
  Emoji('🎒', 'Backpack'),
  Emoji('👞', 'Man’s Shoe'),
  Emoji('👟', 'Running Shoe'),
  Emoji('🥾', 'Hiking Boot'),
  Emoji('🥿', 'Flat Shoe'),
  Emoji('👠', 'High-Heeled Shoe'),
  Emoji('👡', 'Woman’s Sandal'),
  Emoji('👢', 'Woman’s Boot'),
  Emoji('👑', 'Crown'),
  Emoji('👒', 'Woman’s Hat'),
  Emoji('🎩', 'Top Hat'),
  Emoji('🎓', 'Graduation Cap'),
  Emoji('🧢', 'Billed Cap'),
  Emoji('⛑', 'Rescue Worker’s Helmet'),
  Emoji('💄', 'Lipstick'),
  Emoji('💍', 'Ring'),
  Emoji('💼', 'Briefcase')
  ]),

];